services:
  - type: web
    name: vit-sentiment-analyzer
    runtime: python
    branch: clone
    buildCommand: pip install -r requirements.txt && python -m textblob.download_corpora
    startCommand: gunicorn --worker-class gthread --workers 1 --threads 4 --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: FLASK_ENV
        value: production
