services:
  - type: web
    name: vit-sentiment-analyzer
    runtime: python
    branch: clone
    buildCommand: pip install -r requirements.txt && python -m textblob.download_corpora
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
