databases:
  - name: vit-sentiment-db
    databaseName: sentiment_analysis
    user: sentiment_user
    plan: free

services:
  - type: web
    name: vit-sentiment-analyzer
    env: python
    branch: clone
    buildCommand: pip install -r requirements.txt && python -m textblob.download_corpora
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: DATABASE_URL
        fromDatabase:
          name: vit-sentiment-db
          property: connectionString
      - key: FLASK_ENV
        value: production
